import { FormattedValue } from './formatted-value.type';

export interface DefaultKeyStatistics {
  maxAge: number;
  priceHint: FormattedValue;
  enterpriseValue: FormattedValue | object;
  forwardPE: FormattedValue | object;
  profitMargins: FormattedValue | object;
  morningStarOverallRating: FormattedValue | object;
  morningStarRiskRating: FormattedValue | object;
  category: string | null;
  bookValue: FormattedValue | object;
  priceToBook: FormattedValue | object;
  annualReportExpenseRatio: FormattedValue | object;
  ytdReturn: FormattedValue | object;
  qtdReturn: FormattedValue | object;
  beta3Year: FormattedValue | object;
  totalAssets: FormattedValue | object;
  yield: FormattedValue | object;
  fundFamily: string | null;
  fundInceptionDate: FormattedValue | object;
  legalType: string | null;
  threeYearAverageReturn: FormattedValue | object;
  fiveYearAverageReturn: FormattedValue | object;
  priceToSalesTrailing12Months: FormattedValue | object;
  lastFiscalYearEnd: FormattedValue | object;
  nextFiscalYearEnd: FormattedValue | object;
  mostRecentQuarter: FormattedValue | object;
  earningsQuarterlyGrowth: FormattedValue | object;
  revenueQuarterlyGrowth: FormattedValue | object;
  netIncomeToCommon: FormattedValue | object;
  trailingEps: FormattedValue | object;
  forwardEps: FormattedValue | object;
  pegRatio: FormattedValue | object;
  lastSplitFactor: string | null;
  lastSplitDate: FormattedValue | object;
  enterpriseToRevenue: FormattedValue | object;
  enterpriseToEbitda: FormattedValue | object;
  '52WeekChange': FormattedValue;
  SandP52WeekChange: FormattedValue | object;
  lastDividendValue: FormattedValue | object;
  lastDividendDate: FormattedValue | object;
  lastCapGain: FormattedValue | object;
  annualHoldingsTurnover: FormattedValue | object;
  latestFundingDate: FormattedValue | object;
  latestAmountRaised: FormattedValue | object;
  latestImpliedValuation: FormattedValue | object;
  latestShareClass: string | null;
  leadInvestor: string | null;
  fundingToDate: FormattedValue | object;
  totalFundingRounds: FormattedValue | object;
}
