import { FormattedValue } from './formatted-value.type';

export interface SummaryDetail {
  maxAge: number;
  priceHint: FormattedValue;
  previousClose: FormattedValue;
  open: FormattedValue;
  dayLow: FormattedValue;
  dayHigh: FormattedValue;
  regularMarketPreviousClose: FormattedValue;
  regularMarketOpen: FormattedValue;
  regularMarketDayLow: FormattedValue;
  regularMarketDayHigh: FormattedValue;
  dividendRate: FormattedValue | object;
  dividendYield: FormattedValue | object;
  exDividendDate: FormattedValue | object;
  payoutRatio: FormattedValue | object;
  fiveYearAvgDividendYield: FormattedValue | object;
  beta: FormattedValue | object;
  forwardPE: FormattedValue | object;
  volume: FormattedValue;
  regularMarketVolume: FormattedValue;
  averageVolume: FormattedValue;
  averageVolume10days: FormattedValue;
  averageDailyVolume10Day: FormattedValue;
  bid: FormattedValue;
  ask: FormattedValue;
  bidSize: FormattedValue;
  askSize: FormattedValue;
  marketCap: FormattedValue | object;
  yield: FormattedValue | object;
  ytdReturn: FormattedValue | object;
  qtdReturn: FormattedValue | object;
  totalAssets: FormattedValue | object;
  expireDate: FormattedValue | object;
  strikePrice: FormattedValue | object;
  openInterest: FormattedValue | object;
  fiftyTwoWeekLow: FormattedValue;
  fiftyTwoWeekHigh: FormattedValue;
  priceToSalesTrailing12Months: FormattedValue | object;
  fiftyDayAverage: FormattedValue;
  twoHundredDayAverage: FormattedValue;
  trailingAnnualDividendRate: FormattedValue | object;
  trailingAnnualDividendYield: FormattedValue | object;
  navPrice: FormattedValue | object;
  currency: string | null;
  fromCurrency: string | null;
  toCurrency: string | null;
  lastMarket: string | null;
  coinMarketCapLink: string | null;
  volume24Hr: FormattedValue | object;
  volumeAllCurrencies: FormattedValue | object;
  circulatingSupply: FormattedValue | object;
  algorithm: string | null;
  maxSupply: FormattedValue | object;
  startDate: FormattedValue | object;
  tradeable: boolean;
}
